# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last name')),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('hardware_type', models.IntegerField(choices=[(1, 'Car'), (2, 'Motorcycle'), (3, 'Bus')], verbose_name='Hardware type')),
                ('review_date', models.DateField(verbose_name='Review date')),
                ('comments', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Comments')),
            ],
        ),
    ]
